descriptionFormat: '{product.title} - {title}'
enableVersioning: false
handle: products
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: false
maxVariants: null
name: Products
productFieldLayouts:
  be72b007-b301-4d30-82d7-53a0ed9a22ec:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-07T17:05:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: e72f9176-462e-488e-a563-2bbfab3987fe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-07T17:05:11+00:00'
            elementCondition: null
            fieldUid: eb6c8b6c-8a32-42a9-9ab0-97414e63933d # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2b63f9e-e23e-47b6-8ac2-10e82f1ca371
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-07T17:06:52+00:00'
            elementCondition: null
            fieldUid: 58049fbf-27a3-412b-afb4-8810f6d9de2e # Category
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0fedb28-0931-40a6-806f-fb04715be28d
            userCondition: null
            warning: null
            width: 100
          -
            attribute: variants
            dateAdded: '2024-08-07T17:05:11+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: cac72456-60b5-4587-849e-c2ee4c0943e7
            userCondition: null
            warning: null
        name: Content
        uid: a7cd4d02-6bd5-412d-a716-8006b28c5a61
        userCondition: null
productTitleFormat: ''
siteSettings:
  bd3a4e55-c4e4-473f-8a85-dd23d31febdf: # Sprig Training
    hasUrls: true
    template: ''
    uriFormat: 'products/{slug}'
skuFormat: ''
variantFieldLayouts:
  75e4f84e-390a-46aa-b1d5-3fd21ba50086:
    tabs:
      -
        elementCondition: null
        elements:
          -
            attribute: sku
            dateAdded: '2024-08-07T17:05:11+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: SKU
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableSkuField
            uid: 6869f748-80d0-4e9d-8596-d3083ebe8bb0
            userCondition: null
            warning: null
            width: 100
          -
            attribute: price
            dateAdded: '2024-08-07T17:05:11+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: __blank__
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePriceField
            uid: c7f6e0bd-153b-48e2-b16a-02b7831d597d
            userCondition: null
            warning: null
            width: 100
          -
            attribute: stock
            dateAdded: '2024-08-07T17:05:11+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: Inventory
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableStockField
            uid: db54b963-1a5a-4314-92d0-3d694a53f508
            userCondition: null
            warning: null
            width: 100
          -
            attribute: availableForPurchase
            dateAdded: '2024-08-07T17:05:11+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: 'Available for purchase'
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAvailableForPurchaseField
            uid: 0e17c5bd-8c35-499a-9fd5-b95ab7a9e7f3
            userCondition: null
            warning: null
            width: 100
          -
            attribute: allowedQty
            dateAdded: '2024-08-07T17:05:11+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: 'Allowed Qty'
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAllowedQtyField
            uid: c494ea11-e26b-406f-b5dc-743d46d54339
            userCondition: null
            warning: null
            width: 100
          -
            attribute: freeShipping
            dateAdded: '2024-08-07T17:05:11+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: 'Free Shipping'
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableFreeShippingField
            uid: d54be4c1-f121-49e5-9cf5-78d6ec5977d2
            userCondition: null
            warning: null
            width: 100
          -
            attribute: promotable
            dateAdded: '2024-08-07T17:05:11+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: Promotable
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePromotableField
            uid: 2553463e-6793-460a-89e5-55fc16aaf902
            userCondition: null
            warning: null
            width: 100
          -
            attribute: dimensions
            dateAdded: '2024-08-07T17:05:11+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: Dimensions
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableDimensionsField
            uid: 535ec188-4446-425e-9432-1da842424e7c
            userCondition: null
            warning: null
            width: 100
          -
            attribute: weight
            dateAdded: '2024-08-07T17:05:11+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: Weight
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableWeightField
            uid: 38027ea8-565d-4fa2-a9fd-78f0325c6e6d
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-07T17:05:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: 86ffda5f-7f11-4604-bf87-2bbf7ddcb04f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-07T17:05:11+00:00'
            elementCondition: null
            fieldUid: 57dcd468-699f-4123-94e0-7ef4f7c608fa # Colour
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6976c542-7895-445e-a7cc-984f83edc4db
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 828f2570-6e7c-4ce8-b040-9b89c681cdde
        userCondition: null
variantTitleFormat: '{product.title}'
