descriptionFormat: '{product.title} - {title}'
handle: products
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: false
maxVariants: null
name: Products
productFieldLayouts:
  be72b007-b301-4d30-82d7-53a0ed9a22ec:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: e72f9176-462e-488e-a563-2bbfab3987fe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eb6c8b6c-8a32-42a9-9ab0-97414e63933d # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2b63f9e-e23e-47b6-8ac2-10e82f1ca371
            userCondition: null
            warning: null
            width: 100
          -
            attribute: variants
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: cac72456-60b5-4587-849e-c2ee4c0943e7
            userCondition: null
            warning: null
        name: Content
        uid: a7cd4d02-6bd5-412d-a716-8006b28c5a61
        userCondition: null
productTitleFormat: ''
siteSettings:
  bd3a4e55-c4e4-473f-8a85-dd23d31febdf: # Sprig Training
    hasUrls: true
    template: ''
    uriFormat: 'products/{slug}'
skuFormat: ''
variantFieldLayouts:
  75e4f84e-390a-46aa-b1d5-3fd21ba50086:
    tabs:
      -
        elementCondition: null
        elements:
          -
            attribute: sku
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: SKU
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableSkuField
            uid: fa34f245-5678-45b8-bc07-7e56f6cad4b7
            userCondition: null
            warning: null
            width: 100
          -
            attribute: price
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: __blank__
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePriceField
            uid: 26dc65b4-55ec-4c82-a202-868d61548d19
            userCondition: null
            warning: null
            width: 100
          -
            attribute: stock
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: Inventory
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableStockField
            uid: 7be64c0d-5413-432d-8589-472f93ea7fa2
            userCondition: null
            warning: null
            width: 100
          -
            attribute: availableForPurchase
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: 'Available for purchase'
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAvailableForPurchaseField
            uid: 174ae0a4-5d74-48d6-9dfb-a25cbc566824
            userCondition: null
            warning: null
            width: 100
          -
            attribute: allowedQty
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: 'Allowed Qty'
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableAllowedQtyField
            uid: d4f208a8-910a-4d09-802c-68dd89948ea1
            userCondition: null
            warning: null
            width: 100
          -
            attribute: freeShipping
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: 'Free Shipping'
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableFreeShippingField
            uid: 3a793ad1-5b94-42c5-bad2-bdda3a26c91a
            userCondition: null
            warning: null
            width: 100
          -
            attribute: promotable
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: Promotable
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: true
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasablePromotableField
            uid: aa1e364c-3840-49e1-95cd-a7226fb3ffdb
            userCondition: null
            warning: null
            width: 100
          -
            attribute: dimensions
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: Dimensions
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableDimensionsField
            uid: 140985db-67a1-4173-b445-fd6e0b9dd11e
            userCondition: null
            warning: null
            width: 100
          -
            attribute: weight
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: Weight
            mandatory: true
            orientation: null
            providesThumbs: false
            requirable: false
            required: false
            tip: null
            translatable: false
            type: craft\commerce\fieldlayoutelements\PurchasableWeightField
            uid: a77326e1-9040-40da-b902-c1727804eb24
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\VariantTitleField
            uid: 86ffda5f-7f11-4604-bf87-2bbf7ddcb04f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 57dcd468-699f-4123-94e0-7ef4f7c608fa # Colour
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6976c542-7895-445e-a7cc-984f83edc4db
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 828f2570-6e7c-4ce8-b040-9b89c681cdde
        userCondition: null
variantTitleFormat: '{product.title}'
