defaultPlacement: end
enableVersioning: true
entryTypes:
  - b1797aea-7808-418c-a68b-1cb07b2b1c7c # Default
handle: articles
maxAuthors: 1
name: Articles
propagationMethod: all
siteSettings:
  bd3a4e55-c4e4-473f-8a85-dd23d31febdf: # Sprig Training
    enabledByDefault: true
    hasUrls: true
    template: articles/_entry
    uriFormat: 'articles/{slug}'
type: channel
